services:
  - type: web
    name: gemup-marketplace-backend
    env: python
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python -c "import sys; sys.path.insert(0, '.'); sys.path.insert(0, 'app'); from alembic.config import Config; from alembic import command; alembic_cfg = Config('alembic.ini'); command.upgrade(alembic_cfg, 'head')"
    startCommand: python main.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: gemup-marketplace-db
          property: connectionString

databases:
  - name: gemup-marketplace-db
    databaseName: gemup_marketplace
    user: gemup_user
