services:
  # Backend (FastAPI с uv)
  - type: web
    name: gemup-marketplace-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: "uv run uvicorn app.core.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: POSTGRES_HOST
        fromDatabase:
          name: gemup-marketplace-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: gemup-marketplace-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: gemup-marketplace-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: gemup-marketplace-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: gemup-marketplace-db
          property: database
      - key: CORS_ORIGINS
        value: https://gemup-marketplace-frontend.onrender.com

  # Frontend (Next.js через Docker)
  - type: web
    name: gemup-marketplace-frontend
    env: docker
    dockerfilePath: ./nextjs/Dockerfile
    dockerContext: ./nextjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://gemup-marketplace-backend.onrender.com
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://gemup-marketplace-backend.onrender.com

databases:
  - name: gemup-marketplace-db
    databaseName: gemup_marketplace
    user: gemup_user
