"""Fix default values and nullable constraints

Revision ID: 0faaafbe3d08
Revises: 99f794ca3777
Create Date: 2025-05-26 14:52:20.310796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0faaafbe3d08'
down_revision: Union[str, None] = '99f794ca3777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
