"""Add server_default for boolean fields

Revision ID: 7b6395202d50
Revises: fix_boolean_server_defaults
Create Date: 2025-05-26 15:01:51.659990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6395202d50'
down_revision: Union[str, None] = 'fix_boolean_server_defaults'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
