"""Fix default values and nullable constraints

Revision ID: 99f794ca3777
Revises: 60d83fb5fc6e
Create Date: 2025-05-26 14:40:52.741993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99f794ca3777'
down_revision: Union[str, None] = '60d83fb5fc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='orderstatus'),
               nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('proxy_products', 'min_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('proxy_products', 'max_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('proxy_products', 'max_threads',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('proxy_products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('proxy_products', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('proxy_products', 'stock_available',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('proxy_products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('proxy_products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('proxy_purchases', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('proxy_purchases', 'traffic_used_gb',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('proxy_purchases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('proxy_purchases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shopping_carts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shopping_carts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='transactionstatus'),
               nullable=False)
    op.alter_column('transactions', 'payment_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'balance',
               existing_type=sa.NUMERIC(precision=15, scale=8),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_guest',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_guest',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'balance',
               existing_type=sa.NUMERIC(precision=15, scale=8),
               nullable=True)
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'payment_provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='transactionstatus'),
               nullable=True)
    op.alter_column('shopping_carts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('shopping_carts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('proxy_purchases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('proxy_purchases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('proxy_purchases', 'traffic_used_gb',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('proxy_purchases', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('proxy_products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('proxy_products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('proxy_products', 'stock_available',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('proxy_products', 'is_featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('proxy_products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('proxy_products', 'max_threads',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('proxy_products', 'max_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('proxy_products', 'min_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='orderstatus'),
               nullable=True)
    op.alter_column('orders', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
