FROM node:18-alpine

WORKDIR /app

# Установка зависимостей
COPY package*.json ./
RUN npm ci

# Копирование исходного кода
COPY . .

EXPOSE 3000

# Development сервер с hot reload
CMD ["npm", "run", "dev"]
